//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDiem
{
    using System;
    using System.Collections.Generic;
    
    public partial class HocPhan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HocPhan()
        {
            this.KetQuaHocPhan = new HashSet<KetQuaHocPhan>();
        }
    
        public string MaHP { get; set; }
        public string TenHP { get; set; }
        public Nullable<int> SoTC { get; set; }
        public Nullable<int> SoTiet { get; set; }
        public Nullable<double> PhanTramDGK { get; set; }
        public Nullable<double> PhanTramDT { get; set; }
        public string MaHK { get; set; }
        public string ID { get; set; }
    
        public virtual GiangVien GiangVien { get; set; }
        public virtual HocKy HocKy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KetQuaHocPhan> KetQuaHocPhan { get; set; }
    }
}
