//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDiem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuanLyDiemEntities : DbContext
    {
        public QuanLyDiemEntities()
            : base("name=QuanLyDiemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GiangVien> GiangVien { get; set; }
        public virtual DbSet<HocKy> HocKy { get; set; }
        public virtual DbSet<HocPhan> HocPhan { get; set; }
        public virtual DbSet<HocVien> HocVien { get; set; }
        public virtual DbSet<Khoa> Khoa { get; set; }
        public virtual DbSet<LopDaoTao> LopDaoTao { get; set; }
        public virtual DbSet<KetQuaHocPhan> KetQuaHocPhan { get; set; }
    }
}
